# Generated by Django 4.1.3 on 2023-01-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_house_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="house_pics"),
        ),
        migrations.AlterField(
            model_name="house",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
