# Generated by Django 4.1.3 on 2023-01-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_house_image_alter_house_description_alter_house_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="location",
            field=models.JSONField(default=dict, unique=True),
        ),
    ]
