# Generated by Django 4.1.3 on 2023-01-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_house_address_alter_house_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="house",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.house"
            ),
        ),
    ]
