# Generated by Django 4.1.3 on 2023-01-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_profile_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.house",
            ),
        ),
    ]
