# Generated by Django 4.1.3 on 2023-02-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_profile_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="image",
            field=models.ImageField(
                default="house-default.jpg", upload_to="house_pics"
            ),
        ),
    ]
