# Generated by Django 4.1.3 on 2022-12-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_alter_dwelling_owner_alter_dwelling_residents"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dwelling",
        ),
    ]
