# Generated by Django 4.1.3 on 2022-11-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.JSONField(default=dict),
        ),
    ]
