# Generated by Django 4.1.3 on 2022-11-21 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("map", "0002_post_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dwelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=150)),
                ("location", models.JSONField(default=dict)),
                ("description", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "residents",
                    models.ManyToManyField(
                        related_name="owner", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
