# Generated by Django 4.1.3 on 2022-12-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_delete_dwelling"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="location",
            new_name="address",
        ),
    ]
